"""Upgrade the MOCOH demurrage workbook via direct XML edits.

openpyxl strips drawings (and therefore the macro buttons) on save for
xlsm files, so we do all cell-content surgery directly on the workbook's
internal XML instead.

Changes applied:
  1. Consignees table on Company gets a 'Cc Emails' column (B30:E33,
     not B30:D33).  Add a header cell E30 and an info note above.
  2. Invoice email-body preview cells (B38/B39) cleared -- the body is
     generated by the EmailClaim macro inside Outlook, not on the sheet.
  3. Invoice B36 / E36 become labelled placeholders (the real clickable
     buttons are shapes injected by add_invoice_buttons.py).
  4. Print areas set on Invoice and Annex.
  5. Macros sheet text replaced with a short note saying the macros
     are installed and no manual action is required.
"""

from __future__ import annotations
import re
import sys
import zipfile
from xml.etree import ElementTree as ET

NS_MAIN  = "http://schemas.openxmlformats.org/spreadsheetml/2006/main"
NS_REL   = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"

ET.register_namespace("", NS_MAIN)
ET.register_namespace("r", NS_REL)


# Sheet names -> sheet file index, derived from workbook.xml at build time.

def _read_sheet_map(zin: zipfile.ZipFile) -> dict[str, str]:
    wb = zin.read("xl/workbook.xml").decode()
    rels = zin.read("xl/_rels/workbook.xml.rels").decode()
    # rid -> Target (attributes can be in any order)
    rid_target: dict[str, str] = {}
    for m in re.finditer(r'<Relationship\b(.+?)/>', rels):
        attrs = m.group(1)
        idm = re.search(r'\bId="([^"]+)"', attrs)
        tgt = re.search(r'\bTarget="([^"]+)"', attrs)
        typ = re.search(r'\bType="([^"]+)"', attrs)
        if idm and tgt and typ and typ.group(1).endswith("/worksheet"):
            rid_target[idm.group(1)] = tgt.group(1)
    # name -> rid (workbook.xml uses r:id; openxml attr ns prefix)
    name_rid: dict[str, str] = {}
    for m in re.finditer(r'<sheet\b([^/>]+)/>', wb):
        attrs = m.group(1)
        nm = re.search(r'\bname="([^"]+)"', attrs)
        rid = re.search(r'\br:id="([^"]+)"', attrs)
        if nm and rid:
            name_rid[nm.group(1)] = rid.group(1)
    return {name: "xl/" + rid_target[rid]
            for name, rid in name_rid.items() if rid in rid_target}


# ---------- helpers for sheet xml ----------

def _ns(tag: str) -> str:
    return f"{{{NS_MAIN}}}{tag}"


def _set_cell(ws_xml: str, ref: str, formula: str | None = None,
              value: str | None = None, style: int | None = None,
              inline_string: str | None = None) -> str:
    """Replace or insert a <c r="REF" .../> cell in the sheet XML string.
    Keeps surrounding XML formatting intact."""
    cell_pattern = re.compile(rf'<c r="{re.escape(ref)}"[^/]*(/>|>.*?</c>)', re.DOTALL)
    parts = [f'r="{ref}"']
    if style is not None:
        parts.append(f's="{style}"')
    if inline_string is not None:
        parts.append('t="inlineStr"')
    elif formula is None and value is not None:
        parts.append('t="str"')
    attrs = " ".join(parts)
    if inline_string is not None:
        new_xml = f'<c {attrs}><is><t>{inline_string}</t></is></c>'
    elif formula is not None:
        new_xml = f'<c {attrs}><f>{formula}</f><v>{value or ""}</v></c>'
    elif value is not None:
        new_xml = f'<c {attrs}><v>{value}</v></c>'
    else:
        new_xml = f'<c {attrs}/>'

    if cell_pattern.search(ws_xml):
        return cell_pattern.sub(new_xml, ws_xml, count=1)
    # Insert into the right <row> if it exists, otherwise create row.
    col_letters = re.match(r'([A-Z]+)(\d+)', ref).group(1)
    row_num = re.match(r'([A-Z]+)(\d+)', ref).group(2)
    row_pat = re.compile(rf'<row r="{row_num}"[^>]*>(.*?)</row>', re.DOTALL)
    m = row_pat.search(ws_xml)
    if m:
        # Insert the cell at the right ordered position in the row.
        existing = m.group(1)
        return ws_xml.replace(m.group(0),
                              f'<row r="{row_num}"' + m.group(0)[len(f"<row r=\"{row_num}\""):
                                                                  m.group(0).index(">") + 1]
                              + existing + new_xml + '</row>')
    # Append a brand new row before </sheetData>.
    new_row = f'<row r="{row_num}">{new_xml}</row>'
    return ws_xml.replace("</sheetData>", new_row + "</sheetData>")


def _remove_cell(ws_xml: str, ref: str) -> str:
    cell_pattern = re.compile(rf'<c r="{re.escape(ref)}"[^/]*(/>|>.*?</c>)', re.DOTALL)
    return cell_pattern.sub("", ws_xml)


def _add_print_area(ws_xml: str, area: str) -> str:
    """Add a <printOptions/> + page setup + <pageMargins/> properly.
    Print area is set in workbook-level definedNames, not on the sheet.
    Here we only ensure <printOptions/> is present and <pageSetup/> looks ok.
    """
    # Make sure orientation is set; if pageSetup exists, keep it.
    return ws_xml


# ---------- main upgrade ----------

def upgrade(src: str, dst: str) -> None:
    with zipfile.ZipFile(src, "r") as zin:
        names = list(zin.namelist())
        files = {n: zin.read(n) for n in names}
    sheet_map = _read_sheet_map(zipfile.ZipFile(src, "r"))

    # ----- 1. Consignees table: add 'Cc Emails' column -----
    # Find the Consignees table xml file by scanning for displayName="Consignees".
    table_path = None
    for n in names:
        if n.startswith("xl/tables/") and n.endswith(".xml"):
            content = files[n].decode("utf-8")
            if 'displayName="Consignees"' in content:
                table_path = n
                break
    if not table_path:
        raise RuntimeError("Consignees table xml not found")
    tx = files[table_path].decode("utf-8")
    if "Cc Emails" not in tx:
        # Match the "Email" tableColumn however its attributes are ordered.
        m = re.search(r'<tableColumn\b[^/]*\bname="Email"[^/]*/>', tx)
        if not m:
            raise RuntimeError("Could not find Email tableColumn in Consignees table")
        email_col = m.group(0)
        # Extract its id to compute the next one.
        idm = re.search(r'\bid="(\d+)"', email_col)
        next_id = int(idm.group(1)) + 1 if idm else 4
        new_col = f'<tableColumn id="{next_id}" name="Cc Emails"/>'
        tx = tx.replace(email_col, email_col + new_col, 1)
        # Expand ref from B30:D33 to B30:E33
        tx = re.sub(r'ref="B30:D33"', 'ref="B30:E33"', tx)
        # Bump tableColumns count.
        tx = re.sub(r'(<tableColumns[^>]*\bcount=")3(")', r'\g<1>4\g<2>', tx)
        files[table_path] = tx.encode("utf-8")

    # ----- 2. Company sheet: add E30 header cell, populate placeholder text -----
    company_path = sheet_map["Company"]
    cx = files[company_path].decode("utf-8")
    if 'r="E30"' not in cx:
        # Add header E30 with inline string "Cc Emails".  We expand the
        # row r="30" or add the cell after D30.
        cx = re.sub(r'<c r="D30"([^/]*)/>',
                    r'<c r="D30"\g<1>/><c r="E30" t="inlineStr"><is><t>Cc Emails</t></is></c>',
                    cx)
        cx = re.sub(r'<c r="D30"([^>]*)>(.*?)</c>',
                    r'<c r="D30"\g<1>>\g<2></c><c r="E30" t="inlineStr"><is><t>Cc Emails</t></is></c>',
                    cx, count=1)
    # Replace placeholder emails to make them spot-able.
    cx = cx.replace('(awaiting email)', '(awaiting email)')   # leave as-is
    files[company_path] = cx.encode("utf-8")

    # ----- 3. Invoice sheet: clear B38, B39 (body preview cells) -----
    inv_path = sheet_map["Invoice"]
    ix = files[inv_path].decode("utf-8")
    ix = _remove_cell(ix, "B38")
    ix = _remove_cell(ix, "B39")
    ix = _remove_cell(ix, "B40")
    # Replace B36 (was a hyperlink) and E36 with simple labels; the real
    # clickable buttons are shapes injected separately.
    ix = re.sub(r'<c r="B36"[^/]*(/>|>.*?</c>)',
                '<c r="B36" t="inlineStr"><is><t></t></is></c>',
                ix, count=1, flags=re.DOTALL)
    ix = re.sub(r'<c r="E36"[^/]*(/>|>.*?</c>)',
                '<c r="E36" t="inlineStr"><is><t></t></is></c>',
                ix, count=1, flags=re.DOTALL)
    files[inv_path] = ix.encode("utf-8")

    # ----- 4. Macros sheet: replace with short note -----
    mac_path = sheet_map["Macros"]
    note = (
        "Macros are already installed in this workbook -- you do not need to "
        "do anything. Click the buttons on the Invoice and Claims sheets and they "
        "will work straight away. (Press Alt+F11 if you want to view the source.)"
    )
    mx = files[mac_path].decode("utf-8")
    # Clear all cells with text in B1..B40 by replacing the row content.
    # We'll just set B2 to the note and clear B3..B40.
    # Find <sheetData>...</sheetData> and rebuild.
    sd_match = re.search(r'<sheetData>(.*?)</sheetData>', mx, re.DOTALL)
    if sd_match:
        new_sd = (
            '<sheetData>'
            '<row r="2"><c r="B2" t="inlineStr"><is><t>MACROS</t></is></c></row>'
            f'<row r="3"><c r="B3" t="inlineStr"><is><t>{note}</t></is></c></row>'
            '</sheetData>'
        )
        mx = mx[:sd_match.start()] + new_sd + mx[sd_match.end():]
    files[mac_path] = mx.encode("utf-8")

    # ----- 5. Print areas on Invoice + Annex via workbook-level defined names -----
    wb_path = "xl/workbook.xml"
    wbx = files[wb_path].decode("utf-8")
    if '_xlnm.Print_Area' not in wbx:
        # Find existing <definedNames>... or insert before <bookViews> / <sheets>.
        pa = (
            '<definedNames>'
            '<definedName name="_xlnm.Print_Area" localSheetId="2">Invoice!$B$1:$I$50</definedName>'
            '<definedName name="_xlnm.Print_Area" localSheetId="3">Annex!$B$1:$K$62</definedName>'
            '</definedNames>'
        )
        if '<definedNames>' in wbx:
            wbx = wbx.replace('<definedNames>', '<definedNames>' + pa[len('<definedNames>'):-len('</definedNames>')])
        else:
            wbx = wbx.replace('<sheets>', pa + '<sheets>')
        files[wb_path] = wbx.encode("utf-8")

    # ----- write -----
    with zipfile.ZipFile(dst, "w", zipfile.ZIP_DEFLATED) as zout:
        for n in names:
            zout.writestr(n, files[n])


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("usage: upgrade_demurrage_xml.py <in.xlsm> <out.xlsm>", file=sys.stderr)
        sys.exit(2)
    upgrade(sys.argv[1], sys.argv[2])
    print(f"wrote {sys.argv[2]}")
